import re
import os
import time 
import smtplib
from email.message import EmailMessage

class analyser:
    def mailsender(search):
        print("suspsious ip detected ")
        print(f"ip :- {search.group()}")
        with open("threat.txt",'a') as file:
            file.write(f"{search.group()}")
            sender="forbgmiuseonly002@gmail.com"
            key = "feqcikcdywtgoxui"
            reciever="forbgmiuseonly001@gmail.com"
            subject="threat ip detected {search.group()} .... check your server "
            body="ALERT MAIL FROM SERVER "
            msg = EmailMessage()
            msg['subject']=subject
            msg['from']=sender
            msg['to']=reciever
            msg.set_content(body)
                # with open('txt.txt', 'rb') as f:
                #     data = f.read()
                #     name=f.name 
                #     msg.add_attachment(data,maintype="application",subtype="zip", filename=name)
                  # now we establising a mail server using smtp 
            server = smtplib.SMTP("smtp.gmail.com",587)
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(sender,key)
            server.send_message(msg)
            server.quit()
            print("mail sended successfully")
    def __init__(self,file_name):
        self.ippattern=r"\d+\.\d+\.\d+\.\d+"
        self.position = 0
        self.file_name=file_name
        self.count = 0
        self.wait=0
        self.count1=0
        if os.path.exists(file_name) :
            with open(file_name,'r') as f:
                f.seek(0,2)
                self.position=f.tell()
    def analyser(self):
        with open(self.file_name,"r") as f:
            while True:
            
                f.seek(self.position)
                
                line = f.readline()
                ips = re.search(self.ippattern,line)
                if "failed" in line  or "authentication failure" in line or "Invalid user" in line:
                    self.count+=1
                if "failed" in line and ips :
                    self.count1+=1
                if(self.count>=4) or (self.count1>=4):
                    if(self.count1>=4):
                        print("ALERT DETECTED ")
                        self.mailsender(ips)
                        self.count1=0
                    if(self.count>=4):
                        print("ALERT DETECTED ")
                        self.mailsender(ips)
                        self.count=0
                self.position=f.tell()
                if not line:
                    time.sleep(2)
                    self.wait+=1
                    if(self.wait>3):
                        print("waitting for new logs ")
if __name__=="__main__":
    file_name="/var/log/auth.log"
    try :
        monitor=analyser(file_name)    
        monitor.analyser()
    except KeyboardInterrupt:
        print("exit successfully ")

# this is my log monitoring project that used to monitor log of a system (logs are basicaly string generated by a demon of every activity by user ) and send alert  to user via mail by smtp protocol
# i also add a feature if user may want to send mail via file he can send too by just some edit and use by just uncomment the file 
